# Generated by Django 6.0.6 on 2026-07-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_content',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='room_name',
            field=models.CharField(),
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
