# Generated by Django 6.0.6 on 2026-07-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_board_board_content_alter_board_room_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workplace',
            old_name='company',
            new_name='project',
        ),
    ]
