# Generated by Django 6.0.6 on 2026-07-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_company_workplace_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('Content', models.CharField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workplace')),
            ],
        ),
    ]
