# Generated by Django 6.0.6 on 2026-07-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='Content',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='not content'),
            preserve_default=False,
        ),
    ]
