# Generated by Django 6.0.6 on 2026-07-14 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_create_at_note_created_at_remove_note_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='workspace_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workplace')),
            ],
        ),
    ]
