# Generated by Django 6.0.6 on 2026-07-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='workspace_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('work_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.workplace')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
