# Generated by Django 6.0.6 on 2026-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workspacefile_delete_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacefile',
            name='work_place',
            field=models.CharField(max_length=100),
        ),
    ]
