# Generated by Django 6.0.6 on 2026-07-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_workspacefile_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacefile',
            name='work_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.workplace'),
        ),
    ]
