# Generated by Django 6.0.6 on 2026-07-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_workspacefile_work_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacefile',
            name='work_place',
            field=models.CharField(max_length=100),
        ),
    ]
